project:
  type: website
  output-dir: docs

website:
  favicon: logo_2.png
  site-url: "https://cchiquitovalencia.github.io/"
  description: "Un blog para aprender"
  title: "Cristian Chiquito Valencia"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de mi
      #- about.qmd
      #- resources.qmd
      - posts.qmd
  page-footer:
    background: light
    left: 
      - "Copyright 2025, Cristian Chiquito Valencia"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/cchiquitovalencia/
      - icon: github
        href: https://github.com/cchiquitovalencia/
      - icon: envelope-at-fill
        href: mailto:cchiquito.valencia@gmail.com
      - icon: twitter
        href: https://x.com/cchiquitov

format:
  html:
    theme: 
      - flatly
      - styles.scss
    mainfont: Sono
    css: styles.css
    toc: true
    toc-depth: 4
    page-layout: full

editor: visual

language: _language-es.yml

