project:
  type: website
  output-dir: docs

website:
  favicon: logo_2.png
  title: "CHV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - posts.qmd
  page-footer:
    background: light
    left: 
      - "Copyright 2024, Cristian Chiquito Valencia"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/cchiquitovalencia/
      - icon: github
        href: https://github.com/cchiquitovalencia/
      - icon: envelope-at-fill
        href: mailto:cchiquito.valencia@gmail.com
      - icon: twitter
        href: https://x.com/cchiquitov

format:
  html:
    theme: 
      - flatly
      - styles.scss
    mainfont: Sono
    css: styles.css
    toc: true
    page-layout: full

editor: visual

